# Generated by Django 5.1 on 2024-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=10, unique=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sic', models.CharField(blank=True, max_length=10, null=True)),
                ('sic_description', models.CharField(blank=True, max_length=255, null=True)),
                ('insider_transaction_for_owner_exists', models.BooleanField(default=False)),
                ('insider_transaction_for_issuer_exists', models.BooleanField(default=False)),
                ('ein', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('investor_website', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('fiscal_year_end', models.CharField(blank=True, max_length=4, null=True)),
                ('state_of_incorporation', models.CharField(blank=True, max_length=2, null=True)),
                ('state_of_incorporation_description', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing_address', models.TextField(blank=True, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
