# Generated by Django 5.1 on 2024-08-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edgar_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ein',
        ),
        migrations.RemoveField(
            model_name='company',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fiscal_year_end',
        ),
        migrations.RemoveField(
            model_name='company',
            name='insider_transaction_for_issuer_exists',
        ),
        migrations.RemoveField(
            model_name='company',
            name='insider_transaction_for_owner_exists',
        ),
        migrations.RemoveField(
            model_name='company',
            name='investor_website',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='sic_description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state_of_incorporation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state_of_incorporation_description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='cusip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='exchange',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fama_industry',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fama_sector',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, default='Not Specified', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sic_industry',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sic_sector',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(default='Unknown', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='sic',
            field=models.CharField(blank=True, default='0000', max_length=10, null=True),
        ),
    ]
